Using 1 GPU for training... 
training args are: Namespace(batch_size=32, bs_per_gpu=32, calib=False, check_images=False, check_labels=False, conf_file='configs/yolov6l6_finetune.py', data_path='/gpfs/scratch/rayen/YOLOv8/datasets/metatrain/neu_det.yaml', device='0', dist_url='env://', distill=False, distill_feat=False, epochs=300, eval_final_only=False, eval_interval=20, fuse_ab=False, gpu_count=0, heavy_eval_range=50, img_size=320, local_rank=-1, name='train_6l6-32-320', output_dir='results', quant=False, rank=-1, resume=False, save_ckpt_on_last_n_epoch=-1, save_dir='results/train_6l6-32-3201', stop_aug_last_n_epoch=15, teacher_model_path=None, temperature=20, workers=8, world_size=1, write_trainbatch_tb=False)

Train: Checking formats of images with 8 process(es): 
  0%|          | 0/720 [00:00<?, ?it/s]0 image(s) corrupted:   0%|          | 1/720 [00:00<02:35,  4.62it/s]0 image(s) corrupted:  18%|█▊        | 127/720 [00:00<00:01, 488.68it/s]0 image(s) corrupted:  35%|███▌      | 252/720 [00:00<00:00, 738.40it/s]0 image(s) corrupted:  48%|████▊     | 343/720 [00:00<00:00, 734.16it/s]0 image(s) corrupted:  62%|██████▏   | 443/720 [00:00<00:00, 784.86it/s]0 image(s) corrupted:  75%|███████▍  | 539/720 [00:00<00:00, 830.54it/s]0 image(s) corrupted:  87%|████████▋ | 628/720 [00:00<00:00, 847.94it/s]0 image(s) corrupted: 100%|██████████| 720/720 [00:00<00:00, 760.16it/s]
Traceback (most recent call last):
  File "tools/train.py", line 128, in <module>
    main(args)
  File "tools/train.py", line 113, in main
    trainer = Trainer(args, cfg, device)
  File "/gpfs/scratch/rayen/NEU_DET_YOLOV63/yolov6/core/engine.py", line 54, in __init__
    self.train_loader, self.val_loader = self.get_data_loader(args, cfg, self.data_dict)
  File "/gpfs/scratch/rayen/NEU_DET_YOLOV63/yolov6/core/engine.py", line 370, in get_data_loader
    train_loader = create_dataloader(train_path, args.img_size, args.batch_size // args.world_size, grid_size,
  File "/gpfs/scratch/rayen/NEU_DET_YOLOV63/yolov6/data/data_load.py", line 41, in create_dataloader
    dataset = TrainValDataset(
  File "/gpfs/scratch/rayen/NEU_DET_YOLOV63/yolov6/data/datasets.py", line 68, in __init__
    self.img_paths, self.labels = self.get_imgs_labels(self.img_dir)
  File "/gpfs/scratch/rayen/NEU_DET_YOLOV63/yolov6/data/datasets.py", line 281, in get_imgs_labels
    assert "labels" in sub_dirs, f"Could not find a labels directory!"
AssertionError: Could not find a labels directory!
